image: Visual Studio 2017
environment:
  PROJECT_FILE: ./Dict/Dict.csproj
  TEST_PROJECT_FILE: ./Dict.Tests/Dict.Tests.csproj
  CODECOV_REPO_TOKEN:
    secure: E+C3wh/aFQW0FY/2zowCzpcYZi851nRxnbvhXlgQ2tVFGhgh1BI2+Ok0srMDnvgV
build_script:
  - cmd: dotnet build %PROJECT_FILE%
  - cmd: dotnet build %TEST_PROJECT_FILE%
test_script:
  - cmd: dotnet test %TEST_PROJECT_FILE%
  - bash coverage.sh
  - bash codecov.sh